version: '3.5'

services:
  backend:
    build: ./ml-kurkkumopo-backend
    volumes:
      - ./model:/src/model
    ports:
      - 5000:5000 
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  ml:
    build: ./ml-kurkkumopo-training
    volumes:
      - ./model:/src/model
      - ./data:/src/data
      - ./imgs:/src/imgs

