version: '3.5'

services:
  backend:
    image: backend-example-docker
    expose:
      - 8000
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=backend
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    image: frontend-example-docker
    expose:
      - 5000
    environment:
      - API_URL=http://localhost:8000

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend
    container_name: db_backend
    volumes:
      - database:/var/lib/postgresql/data

  proxy: 
    image: jwilder/nginx-proxy 
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80 
    depends_on:
      - backend
      - frontend

volumes:
  database:
