version: '3.5'

services:
  devopsdockeruh_first_volume_exercise:
    image: devopsdockeruh/first_volume_exercise
    volumes:
      - ./logs.txt:/usr/app/logs.txt
    container_name: first_volume_exercise
